-- MySQL Script generated by MySQL Workbench
-- Mon Mar  2 12:37:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabalho` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `trabalho` VARCHAR(45) NOT NULL,
  `resumo` VARCHAR(45) NOT NULL,
  `palavra-chave1` VARCHAR(45) NOT NULL,
  `palavra-chave2` VARCHAR(45) NOT NULL,
  `palavra-chave3` VARCHAR(45) NOT NULL,
  `id_modalidade` INT NOT NULL,
  `id-eixo1` INT NOT NULL,
  `id-eixo2` INT NOT NULL,
  `financiamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`inscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inscrito` (
  `id` INT UNSIGNED NOT NULL,
  `id-modalidade` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nascimento` VARCHAR(45) NOT NULL,
  `nome-social` VARCHAR(45) NOT NULL,
  `instituicao` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL COMMENT 'dúvida se é necessário\n',
  `email` VARCHAR(45) NOT NULL,
  `telefone1` INT NOT NULL,
  `telefone2` INT NULL,
  `raca` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `acessibilidade` VARCHAR(45) NOT NULL,
  `trabalho_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `trabalho_category_id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_inscrito_trabalho_idx` (`trabalho_category_id` ASC) VISIBLE,
  UNIQUE INDEX `id-modalidade_UNIQUE` (`id-modalidade` ASC) VISIBLE,
  CONSTRAINT `fk_inscrito_trabalho`
    FOREIGN KEY (`trabalho_category_id`)
    REFERENCES `mydb`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`config-inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`config-inscritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `faixa-de-preco` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(45) NOT NULL,
  `fim` VARCHAR(45) NOT NULL,
  `comprovante` VARCHAR(45) NOT NULL,
  `inscrito_id` INT UNSIGNED NOT NULL,
  `inscrito_trabalho_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_config-inscritos_inscrito1_idx` (`inscrito_id` ASC, `inscrito_trabalho_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_config-inscritos_inscrito1`
    FOREIGN KEY (`inscrito_id` , `inscrito_trabalho_category_id`)
    REFERENCES `mydb`.`inscrito` (`id` , `trabalho_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`config-congresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`config-congresso` (
  `id` INT NOT NULL COMMENT 'dúvidas se é necessáiro',
  `nome` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(45) NOT NULL,
  `fim` VARCHAR(45) NOT NULL,
  `id-eixos` INT NOT NULL,
  `id-config-inscritos` INT NOT NULL,
  `id-config-trabalhos` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`config-trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`config-trabalho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `início` VARCHAR(45) NOT NULL,
  `fim` VARCHAR(45) NOT NULL,
  `coautores` INT NOT NULL,
  `titulo-min` INT NOT NULL,
  `titulo-max` INT NOT NULL,
  `resumo-min` INT NOT NULL,
  `resumo-max` INT NOT NULL,
  `instrucoes` VARCHAR(45) NOT NULL,
  `trabalho_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_config-trabalho_trabalho1_idx` (`trabalho_id` ASC) VISIBLE,
  CONSTRAINT `fk_config-trabalho_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `mydb`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parecer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parecer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parecer` VARCHAR(45) NOT NULL,
  `texto-parecer` VARCHAR(45) NULL,
  `trabalho_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parecer_trabalho1_idx` (`trabalho_id` ASC) VISIBLE,
  CONSTRAINT `fk_parecer_trabalho1`
    FOREIGN KEY (`trabalho_id`)
    REFERENCES `mydb`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parecerista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parecerista` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `pareceristacol` VARCHAR(45) NOT NULL,
  `parecer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parecerista_parecer1_idx` (`parecer_id` ASC) VISIBLE,
  CONSTRAINT `fk_parecerista_parecer1`
    FOREIGN KEY (`parecer_id`)
    REFERENCES `mydb`.`parecer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`config-parecerista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`config-parecerista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `eixos` VARCHAR(45) NOT NULL,
  `carta` INT NULL,
  `trabalho_category_id` INT UNSIGNED NOT NULL,
  `parecer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `trabalho_category_id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_config-parecerista_trabalho1_idx` (`trabalho_category_id` ASC) VISIBLE,
  INDEX `fk_config-parecerista_parecer1_idx` (`parecer_id` ASC) VISIBLE,
  CONSTRAINT `fk_config-parecerista_trabalho1`
    FOREIGN KEY (`trabalho_category_id`)
    REFERENCES `mydb`.`trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_config-parecerista_parecer1`
    FOREIGN KEY (`parecer_id`)
    REFERENCES `mydb`.`parecerista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `config-inscritos_id` INT NOT NULL,
  `config-congresso_id` INT NOT NULL,
  `config-trabalho_id` INT NOT NULL,
  `config-parecerista_id` INT NOT NULL,
  `config-parecerista_trabalho_category_id` INT UNSIGNED NOT NULL,
  INDEX `fk_admin_config-inscritos1_idx` (`config-inscritos_id` ASC) VISIBLE,
  INDEX `fk_admin_config-congresso1_idx` (`config-congresso_id` ASC) VISIBLE,
  INDEX `fk_admin_config-trabalho1_idx` (`config-trabalho_id` ASC) VISIBLE,
  INDEX `fk_admin_config-parecerista1_idx` (`config-parecerista_id` ASC, `config-parecerista_trabalho_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_config-inscritos1`
    FOREIGN KEY (`config-inscritos_id`)
    REFERENCES `mydb`.`config-inscritos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_config-congresso1`
    FOREIGN KEY (`config-congresso_id`)
    REFERENCES `mydb`.`config-congresso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_config-trabalho1`
    FOREIGN KEY (`config-trabalho_id`)
    REFERENCES `mydb`.`config-trabalho` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_config-parecerista1`
    FOREIGN KEY (`config-parecerista_id` , `config-parecerista_trabalho_category_id`)
    REFERENCES `mydb`.`config-parecerista` (`id` , `trabalho_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`eixos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eixos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
